[build]
  publish = "."
  command = "npx playwright install chromium"
  functions = "netlify/functions"

[functions]
  node_bundler = "nft"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Environment variables (set these in Netlify dashboard)
# QB_URL = "https://sports.yahoo.com/fantasy/article/2025-fantasy-football-rankings-justin-boones-top-quarterbacks-for-week-1-174915206.html"
# RB_URL = "https://sports.yahoo.com/fantasy/article/2025-fantasy-football-rankings-justin-boones-top-running-backs-for-week-1-[ID].html"
# WR_URL = "https://sports.yahoo.com/fantasy/article/2025-fantasy-football-rankings-justin-boones-top-wide-receivers-for-week-1-[ID].html"
# TE_URL = "https://sports.yahoo.com/fantasy/article/2025-fantasy-football-rankings-justin-boones-top-tight-ends-for-week-1-[ID].html"
# FLEX_URL = "https://sports.yahoo.com/fantasy/article/2025-fantasy-football-rankings-justin-boones-top-flex-for-week-1-[ID].html"
# DEF_URL = "https://sports.yahoo.com/fantasy/article/2025-fantasy-football-rankings-justin-boones-top-defenses-for-week-1-[ID].html"
# K_URL = "https://sports.yahoo.com/fantasy/article/2025-fantasy-football-rankings-justin-boones-top-kickers-for-week-1-[ID].html"

# Admin access control
# ADMIN_SECRET_KEY = "your-super-secret-admin-key-here"

# Notification settings (set these in Netlify dashboard)
# ADMIN_EMAIL = "your-email@example.com"              # For email alerts
# DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/..." # For Discord
# SLACK_WEBHOOK_URL = "https://hooks.slack.com/services/..." # For Slack  
# SENDGRID_API_KEY = "SG.xxx"                        # For SendGrid emails
# FROM_EMAIL = "alerts@yoursite.com"                 # From address for emails

# Timestamp-based updater (runs every 3 hours during active period)
[functions."timestamp-updater"]
  schedule = "0 6,9,12,15,18 * * *"  # Every 3 hours from 6 AM to 6 PM ET

